- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: go
  ansible.builtin.import_role:
    name: common
    tasks_from: go

- name: systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd