- name: install maven
  ansible.builtin.dnf:
    name: maven
    state: present

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar file
  ansible.builtin.command: "mv target/{{component}}-{{shipping_version}}.jar {{component}}.jar"
  args:
    chdir: /app

- name: copy shipping service
  ansible.builtin.copy:
    src: shipping.service.j2
    dest: /etc/systemd/system/shipping.service